### ISSUE TITLE
./ImportUrls is killed

### ISSUE THREAD

**Issue by Henner** [MichaelSchoebel/DeuSu#3]
./ImportUrls is killed on execution and nothing happens...

I forked your project and added vagrant. I just wanted to test it but I did noch come very far.
BTW. do you have some more hints for setup?

**Comment by MichaelSchoebel** [comment]
What's "vagrant" ?

Windows or Linux? On Linux you may have to change a setting to allow more open file handles. ImportUrls will open a few more than 1024...

Do you get any error message?

**Comment by Henner** [comment]
linux
nothing in the logs and no error message
Well, I do get it on creating an empty db...


for vagrant see here:
https://www.vagrantup.com
You can now check out the project, cd into vagrant and type vagrant up und you have a running linux box with DeuSu setup.

**Comment by MichaelSchoebel** [comment]
Could be several things. Not enough available file-handles. Out of disk-space. Out of RAM.

I'm assuming you have followed the steps in howto.html including running "makedirs" to create the required subdirectories.

Did you get *any* output from ImportUrls? It will just print any errors to the console.

From a quick glimps at Vagrant I cannot tell if that may add any additional problems.

**Comment by Henner** [comment]
no, vagrant does nothing special. in my case it builds a debian box from scratch and installs what ever you like - see: bootstrap.sh
there is no output at all besides Killed
in no log...
are there any cmd params just printing the version?

**Comment by MichaelSchoebel** [comment]
The very first thing that ImportUrls always does is print its version number. If you are not even seeing that, then there is something very basic going wrong. 64-bit compilation for a 32-bit system or vice versa perhaps?

Where did you fork DeuSu? I can't find it on your Github profile. So I don't know where to look for your bootstrap.sh...

**Comment by Henner** [comment]
https://github.com/mediafactory/DeuSu

**Comment by MichaelSchoebel** [comment]
Change

cd bin
./ImportUrls

to

bin/ImportUrls

Always call the binaries from the base-directory. So always as bin/somebinary. I now see that I at some point changed the directory where the binaries reside from the base-directory to bin and forgot to change the documentation. Oops!

**Comment by Henner** [comment]
does not make any changes.
I now installed 32bit subsystem and still same error

**Comment by Henner** [comment]
bin/Sleep seems to work
bin/Parser seems to work
bin/query dies with:
Recompile the application with a thread-driver in the program uses clause before other units using thread.
Runtime error 232 at $000000000041C103
  $000000000041C103
  $00000000004566EA

**Comment by Henner** [comment]
which FPC version exactly do you use?

**Comment by MichaelSchoebel** [comment]
Do you compile for 32-bit? I don't think that will work. Some of the binaries are very memory hungry. At this moment my crawler is using 17gb RAM. GenDb will use more than 4gb too.

Even if you work on a much smaller scale as I do. The software is written for 64-bit.

**Comment by Henner** [comment]
no, 64bit

**Comment by MichaelSchoebel** [comment]
FPC 3.0.0

**Comment by Henner** [comment]
mine is:
3.0.0+dfsg-9

**Comment by MichaelSchoebel** [comment]
I haven't tested "query" on Linux. I may have missed threading there. It is anyway meant to be run as a CGI invoked by the webserver.

**Comment by MichaelSchoebel** [comment]
ImportUrls will immediately reserve 1gb RAM for a static array. Maybe hitting a limit there?

That would explain why not even the version string appears. It apparently crashes before the main program starts. If you look at it source the first line there is "WriteLn('ImportUrls ', cVersionCopy);".

**Comment by MichaelSchoebel** [comment]
The fix for bin/query is now in the repository. Just a missing

    {$ifdef Unix}
    cthreads,
    {$endif}

right after the "uses" clause.

**Comment by MichaelSchoebel** [comment]
howto.html is updated now as well.

BTW: As far as I know you are the first one besides myself who actually tries to use this. I apparently need to write more documentation to make that easier. Lots of gotchas that I know about, but which are simply ingrained knowledge for me that I don't even consciously think about.

**Comment by Henner** [comment]
i merged that in and rebuild. query seems to work now. dies with:
Content-Type: text/html; charset=UTF-8

An unhandled exception occurred at $000000000044B353:
EFOpenError: Unable to open file "..\..\ranking\general.txt"
  $000000000044B353

wich makes sense.

still no luck with ImportUrls

**Comment by MichaelSchoebel** [comment]
Yep. That's what's to be expected when running query from a commandline.

I still think ImportUrls fails due to lack of RAM. Can you run "free -h" and see what it reports? The software in its current state is intended to run on a root server with at least 32gb RAM.

ImportUrls will need >1gb available for sure. I know 16gb should be plenty enough as that's what I have in my desktop machine. It will need >1024 file handles. So I suggest a "ulimit -n 2048".

**Comment by MichaelSchoebel** [comment]
Another thought... Check "ulimit -a" if it shows any limits for memory usage. "Max locked memory" at 64 is fine and not a problem. But "data seg size", "max memory size" and "virtual memory" could be problematic if there are limits for those. These may not be set on a desktop machine, but could very well be limited in a server or VM environment.

**Comment by Henner** [comment]
no limits:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1912
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 999999
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1912
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

do I really need 32GB to create the empty DB?

**Comment by MichaelSchoebel** [comment]
Not for that. 4gb should probably enough. I tested this on my desktop machine with 16gb RAM, about 6gb were free at the time, and it worked.

I've run out of ideas why this isn't working for you. Sorry.

**Comment by Henner** [comment]
ok got. it really was to less memory assigned to the vm. Sorry for not checking that earlier ...

**Comment by MichaelSchoebel** [comment]
Ok. Good to hear you got over that hurdle. Maybe there will be others yet to come. :) I know I'm horrible at documenting stuff...
